### ISSUE TITLE
Error list

### ISSUE THREAD

**Issue by santhoshnumberone** [amineHY/AI-lab#10]
when I tried to run 

`run /opt/tensorrt/python/python_setup.sh`

I came across 

`ImportError: No module named google.protobuf.internal`

since it is related to `python2`

used to fix the above error

`python -m pip install protobuf`

`numpy` and `tensorflow` gave same error `No Module Found`

tensorflow error
`ImportError: ERROR: Failed to import module (cannot import name 'GraphDef')`

fixed by 
`python -m pip install numpy`

tensorflow error is due to docker from nvidia [Python dependencies for TensorRT container broken](https://devtalk.nvidia.com/default/topic/1064642/docker-and-nvidia-docker/python-dependencies-for-tensorrt-container-broken/)

use 
`python -m pip install tensorflow-gpu==1.15.0`

**Comment by amineHY** [comment]
You do not need to install the requirements that are in `python_setup.sh`. They all have been taken into account in the Dockerfile.
I never ran into the error you are encountering.
So please skip installing `python_setup.sh` and try again.

**Comment by santhoshnumberone** [comment]
I tried skipping the `python_setup.sh`

Went inside 
`YOLOv3-Darknet-ONNX-TensorRT`

ran `python yolov3_to_onnx.py`

no error 

then ran `python onnx_to_tensorrt.py`

I get this error

> Traceback (most recent call last):
>   File "onnx_to_tensorrt.py", line 4, in <module>
>     import common
>   File "/workspace/YOLOv3-Darknet-ONNX-TensorRT/common.py", line 5, in <module>
>     import pycuda.driver as cuda
> ImportError: No module named pycuda.driver

Ran `python -m pip install pycuda`

got this error

> 
> x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -O3 -DNDEBUG -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DBOOST_PYTHON_SOURCE=1 -DHAVE_CURAND=1 -DPYGPU_PACKAGE=pycuda -DBOOST_THREAD_DONT_USE_CHRONO=1 -DPYGPU_PYCUDA=1 -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION=1 -DBOOST_THREAD_BUILD_DLL=1 -Dboost=pycudaboost -DBOOST_ALL_NO_LIB=1 -Isrc/cpp -Ibpl-subset/bpl_subset -I/usr/local/cuda/include -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c src/cpp/cuda.cpp -o build/temp.linux-x86_64-2.7/src/cpp/cuda.o
>     In file included from bpl-subset/bpl_subset/boost/python/detail/prefix.hpp:13:0,
>                      from bpl-subset/bpl_subset/boost/python/args.hpp:8,
>                      from bpl-subset/bpl_subset/boost/python.hpp:11,
>                      from src/cpp/cuda.hpp:36,
>                      from src/cpp/cuda.cpp:4:
>     bpl-subset/bpl_subset/boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory
>     compilation terminated.
>     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tD7Xmm/pycuda/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tD7Xmm/pycuda/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-rqfTtG/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

when i run `python -m pip show pycuda`
i got this 

> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

How do I fix this?

**Comment by amineHY** [comment]
This problem is not related to this GitHub repository.  

In addition, I haven't encountered the issue, the installation of python_setup.sh was always fine on my machine. I am so sorry I can't help you with that.
